{
  global: 
    _JointCommand_default_instance_;
    _ZN12JointCommandD1Ev;
    _ZN12GenericRxMsgC1EPN6google8protobuf5ArenaE;
    _ZN12GenericRxMsg5ClearEv;
    _ZN12GenericRxMsgD1Ev;
    _ZN12JointCommand8CopyFromERKS_;
    _ZN6google8protobuf5Arena18CreateMaybeMessageI3ImuJEEEPT_PS1_DpOT0_;
    _ZN12JointCommandC1EPN6google8protobuf5ArenaE;
    _ZN6google8protobuf5Arena18CreateMaybeMessageI10JointStateJEEEPT_PS1_DpOT0_;
  local: *;
};